Current runner version: '2.334.0' Runner Image Provisioner Operating System Runner Image GITHUB_TOKEN Permissions Secret source: Actions Prepare workflow directory Prepare all required actions Getting action download info Download action repository 'actions/checkout@v4' (SHA:34e114876b0b11c390a56381ad16ebd13914f8d5) Download action repository 'google-github-actions/auth@v2' (SHA:c200f3691d83b41bf9bbd8638997a462592937ed) Download action repository 'google-github-actions/setup-gcloud@v2' (SHA:e427ad8a34f8676edf47cf7d7925499adf3eb74f) Complete job name: build_and_deploy 1s Run actions/checkout@v4 Syncing repository: followsubthai-lgtm/Followsubthai Getting Git version info Temporarily overriding HOME='/home/runner/work/_temp/5cdd0f65-15cb-4b08-a8ac-468c36e49c84' before making global git config changes Adding repository directory to the temporary git global config as a safe directory /usr/bin/git config --global --add safe.directory /home/runner/work/Followsubthai/Followsubthai Deleting the contents of '/home/runner/work/Followsubthai/Followsubthai' Initializing the repository Disabling automatic garbage collection Setting up auth Fetching the repository Determining the checkout info /usr/bin/git sparse-checkout disable /usr/bin/git config --local --unset-all extensions.worktreeConfig Checking out the ref /usr/bin/git log -1 --format=%H d8d3c0fd6c722806ff58d4ab6c4bcc3515ff6f18 1s Run google-github-actions/auth@v2 Created credentials file at "/home/runner/work/Followsubthai/Followsubthai/gha-creds-9026ec436ded3341.json" 14s Run google-github-actions/setup-gcloud@v2   with:     version: latest     skip_install: false     skip_tool_cache: false   env:     CLOUDSDK_AUTH_CREDENTIAL_FILE_OVERRIDE: /home/runner/work/Followsubthai/Followsubthai/gha-creds-9026ec436ded3341.json     GOOGLE_APPLICATION_CREDENTIALS: /home/runner/work/Followsubthai/Followsubthai/gha-creds-9026ec436ded3341.json     GOOGLE_GHA_CREDS_PATH: /home/runner/work/Followsubthai/Followsubthai/gha-creds-9026ec436ded3341.json     CLOUDSDK_CORE_PROJECT: followsubthai-3a814     CLOUDSDK_PROJECT: followsubthai-3a814     GCLOUD_PROJECT: followsubthai-3a814     GCP_PROJECT: followsubthai-3a814     GOOGLE_CLOUD_PROJECT: followsubthai-3a814 /usr/bin/tar xz --warning=no-unknown-keyword --overwrite -C /home/runner/work/_temp/adaf18e6-f440-4390-a244-6283172a3a52 -f /home/runner/work/_temp/e69c6875-42dd-4809-ad87-246b24227fa7 Successfully authenticated 3s Run gcloud artifacts repositories describe followsubthai-repo \   gcloud artifacts repositories describe followsubthai-repo \     --location=asia-southeast1 >nul 2>&1 || \   gcloud artifacts repositories create followsubthai-repo \     --repository-format=docker \     --location=asia-southeast1 \     --description="Demon Subtitle Production Repository"   shell: /usr/bin/bash -e {0}   env:     CLOUDSDK_AUTH_CREDENTIAL_FILE_OVERRIDE: /home/runner/work/Followsubthai/Followsubthai/gha-creds-9026ec436ded3341.json     GOOGLE_APPLICATION_CREDENTIALS: /home/runner/work/Followsubthai/Followsubthai/gha-creds-9026ec436ded3341.json     GOOGLE_GHA_CREDS_PATH: /home/runner/work/Followsubthai/Followsubthai/gha-creds-9026ec436ded3341.json     CLOUDSDK_CORE_PROJECT: followsubthai-3a814     CLOUDSDK_PROJECT: followsubthai-3a814     GCLOUD_PROJECT: followsubthai-3a814     GCP_PROJECT: followsubthai-3a814     GOOGLE_CLOUD_PROJECT: followsubthai-3a814     CLOUDSDK_METRICS_ENVIRONMENT: github-actions-setup-gcloud     CLOUDSDK_METRICS_ENVIRONMENT_VERSION: 2.2.1 1s Run # Build ไปที่ Artifact Registry ของจริง   # Build ไปที่ Artifact Registry ของจริง   gcloud builds submit --tag asia-southeast1-docker.pkg.dev/followsubthai-3a814/followsubthai-repo/webapp .      # Deploy จากคลังใหม่   gcloud run deploy followsubthai \     --image asia-southeast1-docker.pkg.dev/followsubthai-3a814/followsubthai-repo/webapp \     --platform managed \     --region asia-southeast1 \     --allow-unauthenticated \     --port 3000   shell: /usr/bin/bash -e {0}   env:     CLOUDSDK_AUTH_CREDENTIAL_FILE_OVERRIDE: /home/runner/work/Followsubthai/Followsubthai/gha-creds-9026ec436ded3341.json     GOOGLE_APPLICATION_CREDENTIALS: /home/runner/work/Followsubthai/Followsubthai/gha-creds-9026ec436ded3341.json     GOOGLE_GHA_CREDS_PATH: /home/runner/work/Followsubthai/Followsubthai/gha-creds-9026ec436ded3341.json     CLOUDSDK_CORE_PROJECT: followsubthai-3a814     CLOUDSDK_PROJECT: followsubthai-3a814     GCLOUD_PROJECT: followsubthai-3a814     GCP_PROJECT: followsubthai-3a814     GOOGLE_CLOUD_PROJECT: followsubthai-3a814     CLOUDSDK_METRICS_ENVIRONMENT: github-actions-setup-gcloud     CLOUDSDK_METRICS_ENVIRONMENT_VERSION: 2.2.1 ERROR: (gcloud.builds.submit) Invalid value for [source]: Dockerfile required when specifying --tag Error: Process completed with exit code 1. 0s Post job cleanup. Removed exported credentials at "/home/runner/work/Followsubthai/Followsubthai/gha-creds-9026ec436ded3341.json". 0s Post job cleanup. /usr/bin/git version git version 2.54.0 Temporarily overriding HOME='/home/runner/work/_temp/6f9c8a5b-db32-47ea-9a26-b74ac0d04330' before making global git config changes Adding repository directory to the temporary git global config as a safe directory /usr/bin/git config --global --add safe.directory /home/runner/work/Followsubthai/Followsubthai /usr/bin/git config --local --name-only --get-regexp core\.sshCommand /usr/bin/git submodule foreach --recursive sh -c "git config --local --name-only --get-regexp 'core\.sshCommand' && git config --local --unset-all 'core.sshCommand' || :" /usr/bin/git config --local --name-only --get-regexp http\.https\:\/\/github\.com\/\.extraheader http.https://github.com/.extraheader /usr/bin/git config --local --unset-all http.https://github.com/.extraheader /usr/bin/git submodule foreach --recursive sh -c "git config --local --name-only --get-regexp 'http\.https\:\/\/github\.com\/\.extraheader' && git config --local --unset-all 'http.https://github.com/.extraheader' || :" /usr/bin/git config --local --name-only --get-regexp ^includeIf\.gitdir: /usr/bin/git submodule foreach --recursive git config --local --show-origin --name-only --get-regexp remote.origin.url 0s Cleaning up orphan processes Warning: Node.js 20 actions are deprecated. The following actions are running on Node.js 20 and may not work as expected: actions/checkout@v4, google-github-actions/auth@v2, google-github-actions/setup-gcloud@v2. Actions will be forced to run with Node.js 24 by default starting June 2nd, 2026. Node.js 20 will be removed from the runner on September 16th, 2026. Please check if updated versions of these actions are available that support Node.js 24. To opt into Node.js 24 now, set the FORCE_JAVASCRIPT_ACTIONS_TO_NODE24=true environment variable on the runner or in your workflow file. Once Node.js 24 becomes the default, you can temporarily opt out by setting ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION=true. For more information see: https://github.blog/changelog/2025-09-19-deprecation-of-node-20-on-github-actions-runners/
Current runner version: '2.334.0'
Runner Image Provisioner
Operating System
Runner Image
GITHUB_TOKEN Permissions
Secret source: Actions
Prepare workflow directory
Prepare all required actions
Getting action download info
Download action repository 'actions/checkout@v4' (SHA:34e114876b0b11c390a56381ad16ebd13914f8d5)
Download action repository 'google-github-actions/auth@v2' (SHA:c200f3691d83b41bf9bbd8638997a462592937ed)
Download action repository 'google-github-actions/setup-gcloud@v2' (SHA:e427ad8a34f8676edf47cf7d7925499adf3eb74f)
Complete job name: build_and_deploy
1s
Run actions/checkout@v4
Syncing repository: followsubthai-lgtm/Followsubthai
Getting Git version info
Temporarily overriding HOME='/home/runner/work/_temp/5cdd0f65-15cb-4b08-a8ac-468c36e49c84' before making global git config changes
Adding repository directory to the temporary git global config as a safe directory
/usr/bin/git config --global --add safe.directory /home/runner/work/Followsubthai/Followsubthai
Deleting the contents of '/home/runner/work/Followsubthai/Followsubthai'
Initializing the repository
Disabling automatic garbage collection
Setting up auth
Fetching the repository
Determining the checkout info
/usr/bin/git sparse-checkout disable
/usr/bin/git config --local --unset-all extensions.worktreeConfig
Checking out the ref
/usr/bin/git log -1 --format=%H
d8d3c0fd6c722806ff58d4ab6c4bcc3515ff6f18
1s
Run google-github-actions/auth@v2
Created credentials file at "/home/runner/work/Followsubthai/Followsubthai/gha-creds-9026ec436ded3341.json"
14s
Run google-github-actions/setup-gcloud@v2
  with:
    version: latest
    skip_install: false
    skip_tool_cache: false
  env:
    CLOUDSDK_AUTH_CREDENTIAL_FILE_OVERRIDE: /home/runner/work/Followsubthai/Followsubthai/gha-creds-9026ec436ded3341.json
    GOOGLE_APPLICATION_CREDENTIALS: /home/runner/work/Followsubthai/Followsubthai/gha-creds-9026ec436ded3341.json
    GOOGLE_GHA_CREDS_PATH: /home/runner/work/Followsubthai/Followsubthai/gha-creds-9026ec436ded3341.json
    CLOUDSDK_CORE_PROJECT: followsubthai-3a814
    CLOUDSDK_PROJECT: followsubthai-3a814
    GCLOUD_PROJECT: followsubthai-3a814
    GCP_PROJECT: followsubthai-3a814
    GOOGLE_CLOUD_PROJECT: followsubthai-3a814
/usr/bin/tar xz --warning=no-unknown-keyword --overwrite -C /home/runner/work/_temp/adaf18e6-f440-4390-a244-6283172a3a52 -f /home/runner/work/_temp/e69c6875-42dd-4809-ad87-246b24227fa7
Successfully authenticated
3s
Run gcloud artifacts repositories describe followsubthai-repo \
  gcloud artifacts repositories describe followsubthai-repo \
    --location=asia-southeast1 >nul 2>&1 || \
  gcloud artifacts repositories create followsubthai-repo \
    --repository-format=docker \
    --location=asia-southeast1 \
    --description="Demon Subtitle Production Repository"
  shell: /usr/bin/bash -e {0}
  env:
    CLOUDSDK_AUTH_CREDENTIAL_FILE_OVERRIDE: /home/runner/work/Followsubthai/Followsubthai/gha-creds-9026ec436ded3341.json
    GOOGLE_APPLICATION_CREDENTIALS: /home/runner/work/Followsubthai/Followsubthai/gha-creds-9026ec436ded3341.json
    GOOGLE_GHA_CREDS_PATH: /home/runner/work/Followsubthai/Followsubthai/gha-creds-9026ec436ded3341.json
    CLOUDSDK_CORE_PROJECT: followsubthai-3a814
    CLOUDSDK_PROJECT: followsubthai-3a814
    GCLOUD_PROJECT: followsubthai-3a814
    GCP_PROJECT: followsubthai-3a814
    GOOGLE_CLOUD_PROJECT: followsubthai-3a814
    CLOUDSDK_METRICS_ENVIRONMENT: github-actions-setup-gcloud
    CLOUDSDK_METRICS_ENVIRONMENT_VERSION: 2.2.1
1s
Run # Build ไปที่ Artifact Registry ของจริง
  # Build ไปที่ Artifact Registry ของจริง
  gcloud builds submit --tag asia-southeast1-docker.pkg.dev/followsubthai-3a814/followsubthai-repo/webapp .

  # Deploy จากคลังใหม่
  gcloud run deploy followsubthai \
    --image asia-southeast1-docker.pkg.dev/followsubthai-3a814/followsubthai-repo/webapp \
    --platform managed \
    --region asia-southeast1 \
    --allow-unauthenticated \
    --port 3000
  shell: /usr/bin/bash -e {0}
  env:
    CLOUDSDK_AUTH_CREDENTIAL_FILE_OVERRIDE: /home/runner/work/Followsubthai/Followsubthai/gha-creds-9026ec436ded3341.json
    GOOGLE_APPLICATION_CREDENTIALS: /home/runner/work/Followsubthai/Followsubthai/gha-creds-9026ec436ded3341.json
    GOOGLE_GHA_CREDS_PATH: /home/runner/work/Followsubthai/Followsubthai/gha-creds-9026ec436ded3341.json
    CLOUDSDK_CORE_PROJECT: followsubthai-3a814
    CLOUDSDK_PROJECT: followsubthai-3a814
    GCLOUD_PROJECT: followsubthai-3a814
    GCP_PROJECT: followsubthai-3a814
    GOOGLE_CLOUD_PROJECT: followsubthai-3a814
    CLOUDSDK_METRICS_ENVIRONMENT: github-actions-setup-gcloud
    CLOUDSDK_METRICS_ENVIRONMENT_VERSION: 2.2.1
ERROR: (gcloud.builds.submit) Invalid value for [source]: Dockerfile required when specifying --tag
Error: Process completed with exit code 1.
0s
Post job cleanup.
Removed exported credentials at "/home/runner/work/Followsubthai/Followsubthai/gha-creds-9026ec436ded3341.json".
0s
Post job cleanup.
/usr/bin/git version
git version 2.54.0
Temporarily overriding HOME='/home/runner/work/_temp/6f9c8a5b-db32-47ea-9a26-b74ac0d04330' before making global git config changes
Adding repository directory to the temporary git global config as a safe directory
/usr/bin/git config --global --add safe.directory /home/runner/work/Followsubthai/Followsubthai
/usr/bin/git config --local --name-only --get-regexp core\.sshCommand
/usr/bin/git submodule foreach --recursive sh -c "git config --local --name-only --get-regexp 'core\.sshCommand' && git config --local --unset-all 'core.sshCommand' || :"
/usr/bin/git config --local --name-only --get-regexp http\.https\:\/\/github\.com\/\.extraheader
http.https://github.com/.extraheader
/usr/bin/git config --local --unset-all http.https://github.com/.extraheader
/usr/bin/git submodule foreach --recursive sh -c "git config --local --name-only --get-regexp 'http\.https\:\/\/github\.com\/\.extraheader' && git config --local --unset-all 'http.https://github.com/.extraheader' || :"
/usr/bin/git config --local --name-only --get-regexp ^includeIf\.gitdir:
/usr/bin/git submodule foreach --recursive git config --local --show-origin --name-only --get-regexp remote.origin.url
0s
Cleaning up orphan processes
Warning: Node.js 20 actions are deprecated. The following actions are running on Node.js 20 and may not work as expected: actions/checkout@v4, google-github-actions/auth@v2, google-github-actions/setup-gcloud@v2. Actions will be forced to run with Node.js 24 by default starting June 2nd, 2026. Node.js 20 will be removed from the runner on September 16th, 2026. Please check if updated versions of these actions are available that support Node.js 24. To opt into Node.js 24 now, set the FORCE_JAVASCRIPT_ACTIONS_TO_NODE24=true environment variable on the runner or in your workflow file. Once Node.js 24 becomes the default, you can temporarily opt out by setting ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION=true. For more information see: https://github.blog/changelog/2025-09-19-deprecation-of-node-20-on-github-actions-runners/